export const CROP_SLUGS: Record<string, string> = {
  'Пшениця':          'wheat',
  'Пшениця озима':    'winter-wheat',
  'Пшениця яра':      'spring-wheat',
  'Кукурудза':        'corn',
  'Соняшник':         'sunflower',
  'Ріпак':            'rapeseed',
  'Ріпак озимий':     'winter-rapeseed',
  'Ріпак ярий':       'spring-rapeseed',
  'Соя':              'soybean',
  'Ячмінь':           'barley',
  'Ячмінь ярий':      'spring-barley',
  'Ячмінь озимий':    'winter-barley',
  'Жито':             'rye',
  'Жито озиме':       'winter-rye',
  'Буряк':            'sugarbeet',
  'Буряк цукровий':   'sugarbeet',
  'Буряк кормовий':   'fodder-beet',
  'Картопля':         'potato',
  'Томати':           'tomato',
  'Огірки':           'cucumber',
  'Морква':           'carrot',
  'Цибуля':           'onion',
  'Часник':           'garlic',
  'Капуста':          'cabbage',
  'Перець':           'pepper',
  'Полуниця':         'strawberry',
  'Смородина':        'currant',
  'Малина':           'raspberry',
  'Виноград':         'grape',
  'Яблука':           'apple',
  'Груші':            'pear',
  'Черешня':          'cherry',
  'Слива':            'plum',
  'Горох':            'pea',
  'Нут':              'chickpea',
  'Квасоля':          'bean',
  'Сочевиця':         'lentil',
  'Льон':             'flax',
  'Гречка':           'buckwheat',
  'Просо':            'millet',
  'Сорго':            'sorghum',
  'Овес':             'oat',
  'Тритикале озиме':  'winter-triticale',
  'Спельта':          'spelt',
  'Люцерна':          'alfalfa',
  'Вика':             'vetch',
  'Люпин':            'lupine',
  'Гарбузи':          'pumpkin',
  'Кавун':            'watermelon',
  'Гірчиця':          'mustard',
  'Гірчиця біла':     'white-mustard',
  'Коноплі':          'hemp',
  'Амарант':          'amaranth',
  'Рижій':            'camelina',
  'Рис':              'rice',
  'Сориз':            'soriz',
}

// Зворотній маппінг slug → назва
export const SLUG_TO_CROP: Record<string, string> = Object.fromEntries(
  Object.entries(CROP_SLUGS).map(([name, slug]) => [slug, name])
)

export const CROP_EMOJI: Record<string, string> = {
  'Пшениця': '🌾', 'Пшениця озима': '🌾', 'Пшениця яра': '🌾',
  'Кукурудза': '🌽', 'Соняшник': '🌻',
  'Ріпак': '🟡', 'Ріпак озимий': '🟡', 'Ріпак ярий': '🟡',
  'Соя': '🫘', 'Ячмінь': '🌾', 'Ячмінь ярий': '🌾', 'Ячмінь озимий': '🌾',
  'Жито': '🌾', 'Жито озиме': '🌾',
  'Буряк': '🟣', 'Буряк цукровий': '🟣', 'Буряк кормовий': '🟣',
  'Картопля': '🥔', 'Томати': '🍅', 'Огірки': '🥒', 'Морква': '🥕',
  'Цибуля': '🧅', 'Часник': '🧄', 'Капуста': '🥬', 'Перець': '🌶️',
  'Полуниця': '🍓', 'Смородина': '🫐', 'Малина': '🍒', 'Виноград': '🍇',
  'Яблука': '🍎', 'Груші': '🍐', 'Черешня': '🍒', 'Слива': '🍑',
  'Горох': '🫛', 'Нут': '🫘', 'Квасоля': '🫘', 'Сочевиця': '🫘',
  'Льон': '💙', 'Гречка': '⬛', 'Просо': '🌿', 'Сорго': '🌿',
  'Овес': '🌾', 'Тритикале озиме': '🌾', 'Спельта': '🌾',
  'Люцерна': '🌿', 'Вика': '🌿', 'Люпин': '🌿',
  'Гарбузи': '🎃', 'Кавун': '🍉',
  'Гірчиця': '🟤', 'Гірчиця біла': '🟤',
  'Коноплі': '🌿', 'Амарант': '🌺', 'Рижій': '🌿', 'Рис': '🍚',
}

export const cropToSlug = (crop: string): string => CROP_SLUGS[crop] || crop.toLowerCase().replace(/\s+/g, '-')
export const slugToCrop = (slug: string): string => SLUG_TO_CROP[slug] || slug
export const cropEmoji = (crop: string): string => CROP_EMOJI[crop] || '🌱'
